### ISSUE TITLE
Confiused with csv files

### ISSUE THREAD

**Issue by HosseinSheikhi** [denisyarats/drq#15]
Great work!
Am a little confused with the dmc_planet_bench.csv file. Why steps are negative?
To produce results comparable with this csv shall I set the eval_frequency in the config file to 2000?
I want to plot this file using Tensorboard, and just to make sure, shall I set the action_repeat to corresponding action_repeat in table 2 when am going to log this csv with the provided logger? and I have to plot it as eval/episode_reward like following?

`logger.log('eval/episode_reward', float(row['episode_reward']), -1 * int(row['step'])) `

**Comment by denisyarats** [comment]
Please ignore the negative  that was a mistake. You can also use 1000 * row['episode'], or 1000 * row['true_step'].
