### ISSUE TITLE
Getting the code to run deterministically

### ISSUE THREAD

**Issue by snailrowen1337** [denisyarats/drq#18]
I am trying to get the code to run deterministically, i.e. repeat behavior exactly when running the same seed multiple times. However, I'm having some issues. I've tried to disable the cudnn benchmarking:

```
torch.backends.cudnn.benchmark = True
```

I've also added

```
torch.use_deterministic_algorithms(True)
```

Still I am not able to repeat the experiments exactly for fixed seeds. Are there any ideas what further sources of non-determinism in the code base might be? Thanks!!

**Comment by denisyarats** [comment]
Hi,

Unfortunately rendering with EGL seems to be non-deterministic. I've been trying to get to the bottom of this myself a while ago but it does seems it is a bit complicated to do so. Take a look at this issue I created:

https://github.com/deepmind/dm_control/issues/100

**Comment by snailrowen1337** [comment]
Ah got it, thanks!
