### ISSUE TITLE
How to run code without augmentation?

### ISSUE THREAD

**Issue by zhihanyang2022** [denisyarats/drq#19]
Hi, thanks for sharing the code! I'm interested in applying DrQ to a dm_control domain, and I see from the README that I can readily do that using the following command:

```
python train.py env=cartpole_swingup
```

However, is there a way to turn off augmentation (e.g., via command line options)? I'd like to compare the performance with and without augmentation.

**Comment by denisyarats** [comment]
There is a command line option for this, feel free to add one.

Generally, you just need to turn off this:
https://github.com/denisyarats/drq/blob/master/replay_buffer.py#L64
