### ISSUE TITLE
Not learning on dm_control's pendulum swingup

### ISSUE THREAD

**Issue by zhihanyang2022** [denisyarats/drq#20]
Upon running the command

```
python train.py env=pendulum_swingup
```

I'm getting 

![image](https://user-images.githubusercontent.com/43589364/121809516-a4ab2000-cc8f-11eb-9abf-ec0b3fb579b3.png)

I understand that pendulum swingup uses sparse reward, but the agent should be able to earn some reward (although very little) initially by exploration.

**Comment by zhihanyang2022** [comment]
I will train it for longer and come back.

**Comment by KarlXing** [comment]
Hi @zhihanyang2022 , do you have an update for this issue? I have the same problem. The arxiv paper of DrQ-v2 (https://arxiv.org/pdf/2107.09645.pdf) includes DrQ as a benchmark for comparison and shows that DrQ could learn in tasks like pendulum swingup and hopper stand. However, I cannot reproduce the learning with DrQ code.

**Comment by zhihanyang2022** [comment]
@KarlXing It's been a while so I don't remember the exact details, but I recall that DrQ was able to learn in pendulum-swingup after **a very large number of iterations**.  So maybe try doing that?

**Comment by KarlXing** [comment]
@zhihanyang2022 Thanks! I will try to train it longer. Also, I found increasing action repeat could also help.

**Comment by zhihanyang2022** [comment]
@KarlXing Yes, that can make sense since action repeat can improve exploration. After all, pendulum-swingup is sparse reward so things are hard :)
