### ISSUE TITLE
The purpose of layer norm after CNN

### ISSUE THREAD

**Issue by zhihanyang2022** [denisyarats/drq#21]
Hi, I wonder what is the purpose of the layer norm after the convolutional layers. Does it improve stability? 

I understand that your actor and critic are sharing the convolutional layers. Is layer norm for that purpose?

**Comment by denisyarats** [comment]
LN helps to prevent saturation of the consecutive tanh layer.

**Comment by zhihanyang2022** [comment]
Could you help me understand why there's a tanh activation (instead of ReLU) between the CNN encoder and actor/critic?
