### ISSUE TITLE
reproduce problem

### ISSUE THREAD

**Issue by seolhokim** [denisyarats/drq#24]
Can I get all DMC benchmark results if I use `batch_size : 512` and `action_repeat : 8`?
I tried `batch_size : 128` and `action_repeat : 2` in `env : finger`, `task : turn_easy`. But result was bad(under 500 mean score until 200k).

**Comment by denisyarats** [comment]
Hi, I don't have these results. The results from the paper are provided in the repository.

**Comment by seolhokim** [comment]
Hi, Thanks for reply. I just wonder how can I reproduce your performance in finger turn_easy task.

I tried `python train.py` on finger turn_easy task, but result was bad for me.

So I just want to know how did you tune.
