### ISSUE TITLE
About environment steps

### ISSUE THREAD

**Issue by ckdghk77** [denisyarats/drq#25]
Hello, I'm trying to replicate the results of the Dreamer and DrQ papers with PyTorch.

While the DrQ code works fine, I am concerned that the environment steps (x-axis in Figure) are counted differently from Dreamer's.

The Dreamer's implementation increments 1000 environment steps per episode. (No matter what the action repeat is.)
However, in the DrQ implementation, the step count (self.step in train.py) incremented 1000/action_repeat per episode.

I believe that this would make the DrQ consumes more episodes to reach the same training_max_steps.

Am I missing something here?

**Comment by denisyarats** [comment]
Graphs are plotted with action repeat adjustment, i.e. the x-axis multiplied by action repeat.
