### ISSUE TITLE
Action_repeat settings to reproduce your paper results

### ISSUE THREAD

**Issue by teslacool** [denisyarats/drq#5]
In Readme, you mean that if I want to reproduce the results, I just 
`python train.py env=cartpole_swingup batch_size=512`

But I notice the action_repeat number in config.yaml is not 8 for cartpole_swingup.

Maybe you should check this point.

**Comment by denisyarats** [comment]
Yes, `action_repeat` needs to be set according to the paper. See table 2 in the appendix. 

I also update the README. Thanks!

**Comment by teslacool** [comment]
Thanks, this solved my doubt.
