### ISSUE TITLE
eval frequency

### ISSUE THREAD

**Issue by lukashermann** [denisyarats/drq#9]
In line 127 of train.py you are checking if you should evaluate the env (`if self.step % self.cfg.eval_frequency == 0:`).
However, this happens inside the if clause checking for `done`. Shouldn't it be independent of that? Like this, most of the times when `step` is a multiple of `eval_frequency`, it doesn't happen to coincide with `done` being `True`, which means no evaluation will be performed.

**Comment by denisyarats** [comment]
Hi, this is true and in general case (where an episode length can vary) it should be handled by having a separate instance of environment (e.g. `eval_env`). However, in DM control suite each episode is fixed length of 1000, so it doesn't really matter.
